/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AAtribuiConjComandos extends PConjComandos
{
    private PConjComandos _conjComandos_;
    private PComandoAtribuicao _comandoAtribuicao_;

    public AAtribuiConjComandos()
    {
        // Constructor
    }

    public AAtribuiConjComandos(
        @SuppressWarnings("hiding") PConjComandos _conjComandos_,
        @SuppressWarnings("hiding") PComandoAtribuicao _comandoAtribuicao_)
    {
        // Constructor
        setConjComandos(_conjComandos_);

        setComandoAtribuicao(_comandoAtribuicao_);

    }

    @Override
    public Object clone()
    {
        return new AAtribuiConjComandos(
            cloneNode(this._conjComandos_),
            cloneNode(this._comandoAtribuicao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtribuiConjComandos(this);
    }

    public PConjComandos getConjComandos()
    {
        return this._conjComandos_;
    }

    public void setConjComandos(PConjComandos node)
    {
        if(this._conjComandos_ != null)
        {
            this._conjComandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conjComandos_ = node;
    }

    public PComandoAtribuicao getComandoAtribuicao()
    {
        return this._comandoAtribuicao_;
    }

    public void setComandoAtribuicao(PComandoAtribuicao node)
    {
        if(this._comandoAtribuicao_ != null)
        {
            this._comandoAtribuicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoAtribuicao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._conjComandos_)
            + toString(this._comandoAtribuicao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._conjComandos_ == child)
        {
            this._conjComandos_ = null;
            return;
        }

        if(this._comandoAtribuicao_ == child)
        {
            this._comandoAtribuicao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._conjComandos_ == oldChild)
        {
            setConjComandos((PConjComandos) newChild);
            return;
        }

        if(this._comandoAtribuicao_ == oldChild)
        {
            setComandoAtribuicao((PComandoAtribuicao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
