/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AComandoLeia extends PComandoLeia
{
    private TLeia _leia_;
    private TEsqParen _esqParen_;
    private PVarDef _varDef_;
    private TDirParen _dirParen_;
    private TPontoevirgula _pontoevirgula_;

    public AComandoLeia()
    {
        // Constructor
    }

    public AComandoLeia(
        @SuppressWarnings("hiding") TLeia _leia_,
        @SuppressWarnings("hiding") TEsqParen _esqParen_,
        @SuppressWarnings("hiding") PVarDef _varDef_,
        @SuppressWarnings("hiding") TDirParen _dirParen_,
        @SuppressWarnings("hiding") TPontoevirgula _pontoevirgula_)
    {
        // Constructor
        setLeia(_leia_);

        setEsqParen(_esqParen_);

        setVarDef(_varDef_);

        setDirParen(_dirParen_);

        setPontoevirgula(_pontoevirgula_);

    }

    @Override
    public Object clone()
    {
        return new AComandoLeia(
            cloneNode(this._leia_),
            cloneNode(this._esqParen_),
            cloneNode(this._varDef_),
            cloneNode(this._dirParen_),
            cloneNode(this._pontoevirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoLeia(this);
    }

    public TLeia getLeia()
    {
        return this._leia_;
    }

    public void setLeia(TLeia node)
    {
        if(this._leia_ != null)
        {
            this._leia_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leia_ = node;
    }

    public TEsqParen getEsqParen()
    {
        return this._esqParen_;
    }

    public void setEsqParen(TEsqParen node)
    {
        if(this._esqParen_ != null)
        {
            this._esqParen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esqParen_ = node;
    }

    public PVarDef getVarDef()
    {
        return this._varDef_;
    }

    public void setVarDef(PVarDef node)
    {
        if(this._varDef_ != null)
        {
            this._varDef_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varDef_ = node;
    }

    public TDirParen getDirParen()
    {
        return this._dirParen_;
    }

    public void setDirParen(TDirParen node)
    {
        if(this._dirParen_ != null)
        {
            this._dirParen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dirParen_ = node;
    }

    public TPontoevirgula getPontoevirgula()
    {
        return this._pontoevirgula_;
    }

    public void setPontoevirgula(TPontoevirgula node)
    {
        if(this._pontoevirgula_ != null)
        {
            this._pontoevirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoevirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._leia_)
            + toString(this._esqParen_)
            + toString(this._varDef_)
            + toString(this._dirParen_)
            + toString(this._pontoevirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._leia_ == child)
        {
            this._leia_ = null;
            return;
        }

        if(this._esqParen_ == child)
        {
            this._esqParen_ = null;
            return;
        }

        if(this._varDef_ == child)
        {
            this._varDef_ = null;
            return;
        }

        if(this._dirParen_ == child)
        {
            this._dirParen_ = null;
            return;
        }

        if(this._pontoevirgula_ == child)
        {
            this._pontoevirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._leia_ == oldChild)
        {
            setLeia((TLeia) newChild);
            return;
        }

        if(this._esqParen_ == oldChild)
        {
            setEsqParen((TEsqParen) newChild);
            return;
        }

        if(this._varDef_ == oldChild)
        {
            setVarDef((PVarDef) newChild);
            return;
        }

        if(this._dirParen_ == oldChild)
        {
            setDirParen((TDirParen) newChild);
            return;
        }

        if(this._pontoevirgula_ == oldChild)
        {
            setPontoevirgula((TPontoevirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
