/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracoes extends PDeclaracoes
{
    private PDeclaracoes _declaracoes_;
    private PDeclaracaoConj _declaracaoConj_;

    public ADeclaracoes()
    {
        // Constructor
    }

    public ADeclaracoes(
        @SuppressWarnings("hiding") PDeclaracoes _declaracoes_,
        @SuppressWarnings("hiding") PDeclaracaoConj _declaracaoConj_)
    {
        // Constructor
        setDeclaracoes(_declaracoes_);

        setDeclaracaoConj(_declaracaoConj_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracoes(
            cloneNode(this._declaracoes_),
            cloneNode(this._declaracaoConj_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracoes(this);
    }

    public PDeclaracoes getDeclaracoes()
    {
        return this._declaracoes_;
    }

    public void setDeclaracoes(PDeclaracoes node)
    {
        if(this._declaracoes_ != null)
        {
            this._declaracoes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracoes_ = node;
    }

    public PDeclaracaoConj getDeclaracaoConj()
    {
        return this._declaracaoConj_;
    }

    public void setDeclaracaoConj(PDeclaracaoConj node)
    {
        if(this._declaracaoConj_ != null)
        {
            this._declaracaoConj_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracaoConj_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declaracoes_)
            + toString(this._declaracaoConj_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declaracoes_ == child)
        {
            this._declaracoes_ = null;
            return;
        }

        if(this._declaracaoConj_ == child)
        {
            this._declaracaoConj_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declaracoes_ == oldChild)
        {
            setDeclaracoes((PDeclaracoes) newChild);
            return;
        }

        if(this._declaracaoConj_ == oldChild)
        {
            setDeclaracaoConj((PDeclaracaoConj) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
