/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AFacaConjComandos extends PConjComandos
{
    private PConjComandos _conjComandos_;
    private PComandoPara _comandoPara_;

    public AFacaConjComandos()
    {
        // Constructor
    }

    public AFacaConjComandos(
        @SuppressWarnings("hiding") PConjComandos _conjComandos_,
        @SuppressWarnings("hiding") PComandoPara _comandoPara_)
    {
        // Constructor
        setConjComandos(_conjComandos_);

        setComandoPara(_comandoPara_);

    }

    @Override
    public Object clone()
    {
        return new AFacaConjComandos(
            cloneNode(this._conjComandos_),
            cloneNode(this._comandoPara_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFacaConjComandos(this);
    }

    public PConjComandos getConjComandos()
    {
        return this._conjComandos_;
    }

    public void setConjComandos(PConjComandos node)
    {
        if(this._conjComandos_ != null)
        {
            this._conjComandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conjComandos_ = node;
    }

    public PComandoPara getComandoPara()
    {
        return this._comandoPara_;
    }

    public void setComandoPara(PComandoPara node)
    {
        if(this._comandoPara_ != null)
        {
            this._comandoPara_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoPara_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._conjComandos_)
            + toString(this._comandoPara_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._conjComandos_ == child)
        {
            this._conjComandos_ = null;
            return;
        }

        if(this._comandoPara_ == child)
        {
            this._comandoPara_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._conjComandos_ == oldChild)
        {
            setConjComandos((PConjComandos) newChild);
            return;
        }

        if(this._comandoPara_ == oldChild)
        {
            setComandoPara((PComandoPara) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
