/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AMExp extends PExp
{
    private TMenos _menos_;
    private PSomaMenos _somaMenos_;

    public AMExp()
    {
        // Constructor
    }

    public AMExp(
        @SuppressWarnings("hiding") TMenos _menos_,
        @SuppressWarnings("hiding") PSomaMenos _somaMenos_)
    {
        // Constructor
        setMenos(_menos_);

        setSomaMenos(_somaMenos_);

    }

    @Override
    public Object clone()
    {
        return new AMExp(
            cloneNode(this._menos_),
            cloneNode(this._somaMenos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMExp(this);
    }

    public TMenos getMenos()
    {
        return this._menos_;
    }

    public void setMenos(TMenos node)
    {
        if(this._menos_ != null)
        {
            this._menos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menos_ = node;
    }

    public PSomaMenos getSomaMenos()
    {
        return this._somaMenos_;
    }

    public void setSomaMenos(PSomaMenos node)
    {
        if(this._somaMenos_ != null)
        {
            this._somaMenos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._somaMenos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._menos_)
            + toString(this._somaMenos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._menos_ == child)
        {
            this._menos_ = null;
            return;
        }

        if(this._somaMenos_ == child)
        {
            this._somaMenos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._menos_ == oldChild)
        {
            setMenos((TMenos) newChild);
            return;
        }

        if(this._somaMenos_ == oldChild)
        {
            setSomaMenos((PSomaMenos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
