/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AOExpLogica extends PExpLogica
{
    private PExp _exp_;
    private TOu _ou_;
    private PSomaMenos _somaMenos_;

    public AOExpLogica()
    {
        // Constructor
    }

    public AOExpLogica(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TOu _ou_,
        @SuppressWarnings("hiding") PSomaMenos _somaMenos_)
    {
        // Constructor
        setExp(_exp_);

        setOu(_ou_);

        setSomaMenos(_somaMenos_);

    }

    @Override
    public Object clone()
    {
        return new AOExpLogica(
            cloneNode(this._exp_),
            cloneNode(this._ou_),
            cloneNode(this._somaMenos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOExpLogica(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TOu getOu()
    {
        return this._ou_;
    }

    public void setOu(TOu node)
    {
        if(this._ou_ != null)
        {
            this._ou_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ou_ = node;
    }

    public PSomaMenos getSomaMenos()
    {
        return this._somaMenos_;
    }

    public void setSomaMenos(PSomaMenos node)
    {
        if(this._somaMenos_ != null)
        {
            this._somaMenos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._somaMenos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._ou_)
            + toString(this._somaMenos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._ou_ == child)
        {
            this._ou_ = null;
            return;
        }

        if(this._somaMenos_ == child)
        {
            this._somaMenos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._ou_ == oldChild)
        {
            setOu((TOu) newChild);
            return;
        }

        if(this._somaMenos_ == oldChild)
        {
            setSomaMenos((PSomaMenos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
