/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AExpLogica extends PExpLogica
{
    private PExpnLogica _expnLogica_;

    public AExpLogica()
    {
        // Constructor
    }

    public AExpLogica(
        @SuppressWarnings("hiding") PExpnLogica _expnLogica_)
    {
        // Constructor
        setExpnLogica(_expnLogica_);

    }

    @Override
    public Object clone()
    {
        return new AExpLogica(
            cloneNode(this._expnLogica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpLogica(this);
    }

    public PExpnLogica getExpnLogica()
    {
        return this._expnLogica_;
    }

    public void setExpnLogica(PExpnLogica node)
    {
        if(this._expnLogica_ != null)
        {
            this._expnLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expnLogica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expnLogica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expnLogica_ == child)
        {
            this._expnLogica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expnLogica_ == oldChild)
        {
            setExpnLogica((PExpnLogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
