/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AMaiorExpLogica extends PExpLogica
{
    private PExp _exp_;
    private TMaior _maior_;
    private PSomaMenos _somaMenos_;

    public AMaiorExpLogica()
    {
        // Constructor
    }

    public AMaiorExpLogica(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TMaior _maior_,
        @SuppressWarnings("hiding") PSomaMenos _somaMenos_)
    {
        // Constructor
        setExp(_exp_);

        setMaior(_maior_);

        setSomaMenos(_somaMenos_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorExpLogica(
            cloneNode(this._exp_),
            cloneNode(this._maior_),
            cloneNode(this._somaMenos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorExpLogica(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TMaior getMaior()
    {
        return this._maior_;
    }

    public void setMaior(TMaior node)
    {
        if(this._maior_ != null)
        {
            this._maior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maior_ = node;
    }

    public PSomaMenos getSomaMenos()
    {
        return this._somaMenos_;
    }

    public void setSomaMenos(PSomaMenos node)
    {
        if(this._somaMenos_ != null)
        {
            this._somaMenos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._somaMenos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._maior_)
            + toString(this._somaMenos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._maior_ == child)
        {
            this._maior_ = null;
            return;
        }

        if(this._somaMenos_ == child)
        {
            this._somaMenos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._maior_ == oldChild)
        {
            setMaior((TMaior) newChild);
            return;
        }

        if(this._somaMenos_ == oldChild)
        {
            setSomaMenos((PSomaMenos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
