/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class ARepitaConjComandos extends PConjComandos
{
    private PConjComandos _conjComandos_;
    private PComandoRepita _comandoRepita_;

    public ARepitaConjComandos()
    {
        // Constructor
    }

    public ARepitaConjComandos(
        @SuppressWarnings("hiding") PConjComandos _conjComandos_,
        @SuppressWarnings("hiding") PComandoRepita _comandoRepita_)
    {
        // Constructor
        setConjComandos(_conjComandos_);

        setComandoRepita(_comandoRepita_);

    }

    @Override
    public Object clone()
    {
        return new ARepitaConjComandos(
            cloneNode(this._conjComandos_),
            cloneNode(this._comandoRepita_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARepitaConjComandos(this);
    }

    public PConjComandos getConjComandos()
    {
        return this._conjComandos_;
    }

    public void setConjComandos(PConjComandos node)
    {
        if(this._conjComandos_ != null)
        {
            this._conjComandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conjComandos_ = node;
    }

    public PComandoRepita getComandoRepita()
    {
        return this._comandoRepita_;
    }

    public void setComandoRepita(PComandoRepita node)
    {
        if(this._comandoRepita_ != null)
        {
            this._comandoRepita_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoRepita_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._conjComandos_)
            + toString(this._comandoRepita_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._conjComandos_ == child)
        {
            this._conjComandos_ = null;
            return;
        }

        if(this._comandoRepita_ == child)
        {
            this._comandoRepita_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._conjComandos_ == oldChild)
        {
            setConjComandos((PConjComandos) newChild);
            return;
        }

        if(this._comandoRepita_ == oldChild)
        {
            setComandoRepita((PComandoRepita) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
