/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AVazioExpnLogica extends PExpnLogica
{

    public AVazioExpnLogica()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AVazioExpnLogica();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVazioExpnLogica(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
