/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.node;

import portugol.analysis.*;

@SuppressWarnings("nls")
public final class AVetorVarDef extends PVarDef
{
    private TIdentificador _identificador_;
    private TEsqColchete _esqColchete_;
    private TNInt _nInt_;
    private TDirColchete _dirColchete_;

    public AVetorVarDef()
    {
        // Constructor
    }

    public AVetorVarDef(
        @SuppressWarnings("hiding") TIdentificador _identificador_,
        @SuppressWarnings("hiding") TEsqColchete _esqColchete_,
        @SuppressWarnings("hiding") TNInt _nInt_,
        @SuppressWarnings("hiding") TDirColchete _dirColchete_)
    {
        // Constructor
        setIdentificador(_identificador_);

        setEsqColchete(_esqColchete_);

        setNInt(_nInt_);

        setDirColchete(_dirColchete_);

    }

    @Override
    public Object clone()
    {
        return new AVetorVarDef(
            cloneNode(this._identificador_),
            cloneNode(this._esqColchete_),
            cloneNode(this._nInt_),
            cloneNode(this._dirColchete_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVetorVarDef(this);
    }

    public TIdentificador getIdentificador()
    {
        return this._identificador_;
    }

    public void setIdentificador(TIdentificador node)
    {
        if(this._identificador_ != null)
        {
            this._identificador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificador_ = node;
    }

    public TEsqColchete getEsqColchete()
    {
        return this._esqColchete_;
    }

    public void setEsqColchete(TEsqColchete node)
    {
        if(this._esqColchete_ != null)
        {
            this._esqColchete_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esqColchete_ = node;
    }

    public TNInt getNInt()
    {
        return this._nInt_;
    }

    public void setNInt(TNInt node)
    {
        if(this._nInt_ != null)
        {
            this._nInt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nInt_ = node;
    }

    public TDirColchete getDirColchete()
    {
        return this._dirColchete_;
    }

    public void setDirColchete(TDirColchete node)
    {
        if(this._dirColchete_ != null)
        {
            this._dirColchete_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dirColchete_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identificador_)
            + toString(this._esqColchete_)
            + toString(this._nInt_)
            + toString(this._dirColchete_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identificador_ == child)
        {
            this._identificador_ = null;
            return;
        }

        if(this._esqColchete_ == child)
        {
            this._esqColchete_ = null;
            return;
        }

        if(this._nInt_ == child)
        {
            this._nInt_ = null;
            return;
        }

        if(this._dirColchete_ == child)
        {
            this._dirColchete_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identificador_ == oldChild)
        {
            setIdentificador((TIdentificador) newChild);
            return;
        }

        if(this._esqColchete_ == oldChild)
        {
            setEsqColchete((TEsqColchete) newChild);
            return;
        }

        if(this._nInt_ == oldChild)
        {
            setNInt((TNInt) newChild);
            return;
        }

        if(this._dirColchete_ == oldChild)
        {
            setDirColchete((TDirColchete) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
