/* This file was generated by SableCC (http://www.sablecc.org/). */

package portugol.analysis;

import portugol.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTFim(TFim node);
    void caseTVar(TVar node);
    void caseTInicio(TInicio node);
    void caseTPrograma(TPrograma node);
    void caseTEscreva(TEscreva node);
    void caseTInteiro(TInteiro node);
    void caseTReal(TReal node);
    void caseTCaractere(TCaractere node);
    void caseTSe(TSe node);
    void caseTFimSe(TFimSe node);
    void caseTEntao(TEntao node);
    void caseTSenao(TSenao node);
    void caseTAvalie(TAvalie node);
    void caseTFimAvalie(TFimAvalie node);
    void caseTEnquanto(TEnquanto node);
    void caseTFaca(TFaca node);
    void caseTFimEnquanto(TFimEnquanto node);
    void caseTRepita(TRepita node);
    void caseTAte(TAte node);
    void caseTPara(TPara node);
    void caseTFimPara(TFimPara node);
    void caseTMais(TMais node);
    void caseTMenos(TMenos node);
    void caseTMult(TMult node);
    void caseTAtribuicao(TAtribuicao node);
    void caseTComma(TComma node);
    void caseTColon(TColon node);
    void caseTSemicolon(TSemicolon node);
    void caseTLParen(TLParen node);
    void caseTRParen(TRParen node);
    void caseTAspaD(TAspaD node);
    void caseTAspaS(TAspaS node);
    void caseTLColchete(TLColchete node);
    void caseTRColchete(TRColchete node);
    void caseTIgual(TIgual node);
    void caseTMaior(TMaior node);
    void caseTMenor(TMenor node);
    void caseTMaioriagual(TMaioriagual node);
    void caseTMenorigual(TMenorigual node);
    void caseTDiferente(TDiferente node);
    void caseTIdentificador(TIdentificador node);
    void caseTBlanks(TBlanks node);
    void caseTNumero(TNumero node);
    void caseTComment(TComment node);
    void caseTCommentEnd(TCommentEnd node);
    void caseTCommentBody(TCommentBody node);
    void caseTStar(TStar node);
    void caseTSlash(TSlash node);
    void caseTComentarioSimples(TComentarioSimples node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
